#ifndef __N_MIDI_PROG_H__
#define __N_MIDI_PROG_H__

#include <nall/platform.hpp>

using namespace nall;

namespace MIDI {
	enum DrumKit : uint8_t {
		Standard = 0,
		Standard2,
		Room = 8,
		Power = 16,
		Electronic = 24,
		TR808,
		Jazz = 32,
		Brush = 40,
		Orchestral = 48,
		FX = 56,
		CM64 = 127
	};
	const string DrumKitName[] = {
		"Standard",
		"Standard 2",
		"","","","","","",
		"Room",
		"","","","","","","",
		"Power",
		"","","","","","","",
		"Electronic",
		"TR-808",
		"","","","","","",
		"Jazz",
		"","","","","","","",
		"Brush",
		"","","","","","","",
		"Orchestral",
		"","","","","","","",
		"Sound FX",
		"","","","","","","",
		"","","","","","","","",
		"","","","","","","","",
		"","","","","","","","",
		"","","","","","","","",
		"","","","","","","","",
		"","","","","","","","",
		"","","","","","","","",
		"","","","","","","",
		"CM-64"
	};
	enum Patch : uint8_t {
		// piano
		PianoAcGrand = 0,
		PianoAcUpright,
		PianoElGrand,
		PianoHT,
		PianoElRhodes,
		PianoElChorus,
		Harpsichord,
		Clavinet,
		// chrom perc
		Celesta,
		Glockenspiel,
		MusicBox,
		Vibraphone,
		Marimba,
		Xylophone,
		Bells,
		Dulcimer,
		// organ
		OrganHammond,
		OrganB3,
		OrganB3Leslie,
		OrganPipe,
		OrganReed,
		Accordion,
		Harmonica,
		Bandoneon,	// aka tango accordion, concertina
		// guitar
		GuitarAcNylon,
		GuitarAcSteel,
		GuitarElJazz,
		GuitarElClean,
		GuitarElMuted,
		GuitarElOverdriven,
		GuitarElDistorted,
		GuitarElHarmonics,
		// bass
		BassAc,
		BassElFingered,
		BassElPicked,
		BassElFretless,
		BassElSlap1,
		BassElSlap2,
		BassSynth1,
		BassSynth2,
		// string, concert
		Violin,
		Viola,
		Cello,
		Contrabass,	// aka double bass
		StringsTremolo,
		StringsPizzicato,
		Harp,
		Timpani,	// aka kettle drum
		// ensemble
		StringsEns1,
		StringsEns2,
		StringsSynth1,
		StringsSynth2,
		EnsembleAahs,
		EnsembleOohs,
		EnsembleVox,
		EnsembleHit,
		// brass
		Trumpet,
		Trombone,
		Tuba,
		TrumpetMuted,
		HornFrench,
		EnsembleBrass,
		BrassSynth1,
		BrassSynth2,
		// woodwind
		SaxSoprano,
		SaxAlto,
		SaxTenor,
		SaxBaritone,
		Oboe,
		HornEnglish,
		Bassoon,
		Clarinet,
		// wind
		Piccolo,
		Flute,
		Recorder,
		FlutePan,
		Bottle,
		FluteBamboo,	// aka shakuhachi
		Whistle,
		Ocarina,
		// synth lead
		LeadSquare,
		LeadSaw,
		LeadCalliope,
		LeadChiff,
		LeadCharanga,
		LeadVox,
		LeadFifths,
		LeadBass,
		// synth pad
		PadNewage,
		PadWarm,
		PadPoly,
		PadVox,
		PadBowed,
		PadMetal,
		PadHalo,
		PadSweep,
		// synth fx
		SFXRain,
		SFXSoundtrack,
		SFXCrystal,
		SFXAtmosphere,
		SFXBrightness,
		SFXGoblins,
		SFXEchoes,
		SFXScifi,
		// ethnic
		Sitar,
		Banjo,
		Shamisen,
		Koto,
		Kalimba,
		Bagpipe,
		Fiddle,
		Shanai,
		// perc
		Tinkle,
		Agogo,
		Steeldrum,
		Woodblock,
		Taiko,
		Tom,
		Synthdrum,
		// sfx
		FXReverseCymbal,
		FXGuitarFret,
		FXBreath,
		FXSeashore,
		FXTweet,
		FXTelephone,
		FXHelicopter,
		FXApplause,
		FXGunshot,
		count
	};
	const string ProgramName[] = {
		// piano
		"Acoustic Grand Piano",
		"Acoustic Upright Piano",
		"Electric Grand Piano",
		"Honky-Tonk Piano",
		"Electric Piano (Rhodes)",
		"Electric Piano (Chorused)",
		"Harpsichord",
		"Clavinet",
		// chrom perc
		"Celesta",
		"Glockenspiel",
		"Music Box",
		"Vibraphone",
		"Marimba",
		"Xylophone",
		"Tubular Bells",
		"Dulcimer",
		// organ
		"Hammond Organ",
		"Hammond Organ (Percussive)",
		"Hammond Organ (Leslie)",
		"Pipe Organ",
		"Reed Organ",
		"Accordion",
		"Harmonica",
		"Bandoneon",	// aka tango accordion, concertina
		// guitar
		"Acoustic Guitar (Nylon)",
		"Acoustic Guitar (Steel)",
		"Electric Guitar (Jazz)",
		"Electric Guitar (Clean)",
		"Electric Guitar (Muted)",
		"Electric Guitar (Overdriven)",
		"Electric Guitar (Distorted)",
		"Electric Guitar (Harmonics)",
		// bass
		"Acoustic Bass",
		"Electric Bass (Fingered)",
		"Electric Bass (Picked)",
		"Electric Bass (Fretless)",
		"Electric Bass (Slap 1)",
		"Electric Bass (Slap 2)",
		"Synth Bass 1",
		"Synth Bass 2",
		// string, concert
		"Violin",
		"Viola",
		"Cello",
		"Double Bass",	// aka double bass
		"Concert Strings (Tremolo)",
		"Concert Strings (Pizzicato)",
		"Concert Harp",
		"Concert Timpani",	// aka kettle drum
		// ensemble
		"Ensemble Strings (Quick)",
		"Ensemble Strings (Slow)",
		"Synth Strings (Quick)",
		"Synth Strings (Slow)",
		"Ensemble Aahs",
		"Ensemble Oohs",
		"Ensemble Vox",
		"Ensemble Hit",
		// brass
		"Trumpet",
		"Trombone",
		"Tuba",
		"Trumpet (Muted)",
		"French Horn",
		"Ensemble Brass",
		"Synth Brass 1",
		"Synth Brass 2",
		// woodwind
		"Saxophone (Soprano)",
		"Saxophone (Alto)",
		"Saxophone (Tenor)",
		"Saxophone (Baritone)",
		"Oboe",
		"Cor Anglais",
		"Bassoon",
		"Clarinet",
		// wind
		"Piccolo",
		"Flute",
		"Recorder",
		"Pan Pipe",
		"Bottle Blow",
		"Shakuhachi",	// aka shakuhachi
		"Whistle",
		"Ocarina",
		// synth lead
		"Lead (Square)",
		"Lead (Sawtooth)",
		"Lead (Calliope)",
		"Lead (Chiff)",
		"Lead (Charanga)",
		"Lead (Vox)",
		"Lead (Fifths)",
		"Lead (Bass+Lead)",
		// synth pad
		"Pad (New Age)",
		"Pad (Warm)",
		"Pad (Polysynth)",
		"Pad (Vox)",
		"Pad (Bowed Glass)",
		"Pad (Metal)",
		"Pad (Halo)",
		"Pad (Sweep)",
		// synth fx
		"SFX (Ice Rain)",
		"SFX (Soundtrack)",
		"SFX (Crystal)",
		"SFX (Atmosphere)",
		"SFX (Brightness)",
		"SFX (Goblins)",
		"SFX (Echoes)",
		"SFX (Sci-Fi)",
		// ethnic
		"Sitar",
		"Banjo",
		"Shamisen",
		"Koto",
		"Kalimba",
		"Bagpipe",
		"Fiddle",
		"Shanai",
		// perc
		"Tinkle",
		"Agogo",
		"Steel Drums",
		"Woodblock",
		"Taiko",
		"Toms",
		"Synth Drum",
		// sfx
		"Reverse Cymbal",
		"Guitar Fret",
		"Breath Noise",
		"Seashore",
		"Bird Tweet",
		"Telephone",
		"Helicopter",
		"Applause",
		"Gunshot"
	};
}

#endif